apiVersion: v1
kind: Service
metadata:
  name: pythonapi-svc
  namespace: pythonapi
  labels:
    app: pythonapi
spec:
  type: NodePort
  ports:
  - name: http
    port: 5000
    #targetPort: 5000
    nodePort: 30087
  selector:
    app: pythonapi
